object Versions {

    const val coreKtx = "1.9.0"
    const val appcompat = "1.6.1"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.8.1"
    const val composeBom = "2023.03.00"
    const val junit = "4.13.2"
    const val testJunit = "1.1.5"
    const val testEspresso = "3.5.1"
    const val material = "1.10.0"
    const val hiltVersion = "2.48.1"
    const val hiltNavigationVersion = "1.1.0"
    const val navigationCompose = "2.7.5"
    const val retrofitVersion ="2.9.0"
    const val okhttpBom ="4.10.0"
    const val okhttp ="5.0.0-alpha.2"
    const val moshi ="1.14.0"
    const val moshiConverter="2.9.0"
    const val coroutines="1.3.9"
    const val coil ="2.2.0"
    const val splashScreen = "1.0.1"
}